name: Setup Synapse
description: Deploys a synapse test server
inputs:
  installer:
    description: Installer
    required: false
    default: "pip"
  uploadLogs:
    description: Upload synapse logs at end
    required: false
    default: "false"
  artifactName:
    description: Override artifact name for logs
    required: false
    default: "synapse-logs"
  artifactRetentionDays:
    description: Artifact retention days
    required: false
    default: "0"
  customConfig:
    description: JSON-formatted custom config for synapse
    required: false
    default: '{}'
  customModules:
    description: Comma-separated list of modules to pip install.
    required: false
    default: ''
  publicBaseurl:
    description: "Public base URL (defaults to http://localhost:${httpPort} if not defined)"
    required: false
  httpPort:
    description: HTTP port for C-S and S-S APIs
    required: false
    default: "8080"
  disableRateLimiting:
    description: Disable ratelimiting of server requests
    required: false
    default: "true"
runs:
  using: node20
  main: dist/create/index.js
  post: dist/destroy/index.js
  post-if: always()
