name: 'Setup Synapse'
description: 'Deploys a synapse test server and provides the homeserver URL'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
outputs:
  homeserver: # output will be available to future steps
    description: 'Homeserver URL for clients'
runs:
  using: 'node16'
  main: 'dist/create/index.js'
  post: 'dist/destroy/index.js'
  post-if: 'always()'
