name: 'Setup Synapse'
description: 'Deploys a synapse test server'
inputs:
  uploadLogs:
    description: 'Upload synapse logs at end'
    required: true
    default: true
  artifactName:
    description: 'Override artifact name for logs'
    required: false
    default: 'synapse-logs'

runs:
  using: 'node16'
  main: 'dist/create/index.js'
  post: 'dist/destroy/index.js'
  post-if: 'always()'
