name: "units-test"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ">=3.9"
    - name: Run synapse
      uses: ./
      with: 
        uploadLogs: true
        artifactName: test-${{ github.run_id }}-${{ github.run_attempt }}
        artifactRetentionDays: 1
        httpPort: 8008
  
  test-poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ">=3.9"
    - name: Run synapse
      uses: ./
      with: 
        uploadLogs: true
        artifactName: test-poetry-${{ github.run_id }}-${{ github.run_attempt }}
        artifactRetentionDays: 1
        httpPort: 8008
        installer: "poetry"
  
  test-baseurl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ">=3.9"
    - name: Run synapse
      uses: ./
      with: 
        uploadLogs: true
        artifactName: test-baseurl-${{ github.run_id }}-${{ github.run_attempt }}
        artifactRetentionDays: 1
        httpPort: 8008
        publicBaseurl: http://10.0.2.2:8008/
  
  test-modules-poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ">=3.9"
    - name: Run synapse
      uses: ./
      with: 
        installer: poetry
        uploadLogs: true
        artifactName: test-modules-poetry-${{ github.run_id }}-${{ github.run_attempt }}
        artifactRetentionDays: 1
        httpPort: 8008
        customModules: "git+https://github.com/michaelkaye/noop-synapse-storage-provider.git"
        customConfig: | 
          media_storage_providers:
            - module: noop_storage_provider.NoopStorageProviderBackend
              store_local: True
              store_remote: True
              store_synchronous: True
              config:
                sample: "sample"
    - name: Wait for synapse to do something
      run: sleep 60

  test-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ">=3.9"
    - name: Run synapse
      uses: ./
      with: 
        uploadLogs: true
        artifactName: test-modules-${{ github.run_id }}-${{ github.run_attempt }}
        artifactRetentionDays: 1
        httpPort: 8008
        customModules: "git+https://github.com/michaelkaye/noop-synapse-storage-provider.git#egg=noop-synapse-storage-provider"
        customConfig: | 
          media_storage_providers:
            - module: noop_storage_provider.NoopStorageProviderBackend
              store_local: True
              store_remote: True
              store_synchronous: True
              config:
                sample: "sample"
    - name: Wait for synapse to do something
      run: sleep 60
